/* 
 * ChannelEngine Channel API
 *
 * ChannelEngine API for channels
 *
 * OpenAPI spec version: 2.5.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using ChannelEngine.Channel.ApiClient.Client;
using ChannelEngine.Channel.ApiClient.Model;

namespace ChannelEngine.Channel.ApiClient.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICancellationApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get Cancellations
        /// </summary>
        /// <remarks>
        /// Gets all cancellations created since the supplied date.
        /// </remarks>
        /// <exception cref="ChannelEngine.Channel.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createdSince"></param>
        /// <returns>CollectionOfChannelCancellationResponse</returns>
        CollectionOfChannelCancellationResponse CancellationIndex (DateTime? createdSince);

        /// <summary>
        /// Get Cancellations
        /// </summary>
        /// <remarks>
        /// Gets all cancellations created since the supplied date.
        /// </remarks>
        /// <exception cref="ChannelEngine.Channel.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createdSince"></param>
        /// <returns>ApiResponse of CollectionOfChannelCancellationResponse</returns>
        ApiResponse<CollectionOfChannelCancellationResponse> CancellationIndexWithHttpInfo (DateTime? createdSince);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get Cancellations
        /// </summary>
        /// <remarks>
        /// Gets all cancellations created since the supplied date.
        /// </remarks>
        /// <exception cref="ChannelEngine.Channel.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createdSince"></param>
        /// <returns>Task of CollectionOfChannelCancellationResponse</returns>
        System.Threading.Tasks.Task<CollectionOfChannelCancellationResponse> CancellationIndexAsync (DateTime? createdSince);

        /// <summary>
        /// Get Cancellations
        /// </summary>
        /// <remarks>
        /// Gets all cancellations created since the supplied date.
        /// </remarks>
        /// <exception cref="ChannelEngine.Channel.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createdSince"></param>
        /// <returns>Task of ApiResponse (CollectionOfChannelCancellationResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CollectionOfChannelCancellationResponse>> CancellationIndexAsyncWithHttpInfo (DateTime? createdSince);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CancellationApi : ICancellationApi
    {
        private ChannelEngine.Channel.ApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CancellationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CancellationApi(String basePath)
        {
            this.Configuration = new ChannelEngine.Channel.ApiClient.Client.Configuration { BasePath = basePath };

            ExceptionFactory = ChannelEngine.Channel.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CancellationApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public CancellationApi(ChannelEngine.Channel.ApiClient.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = ChannelEngine.Channel.ApiClient.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = ChannelEngine.Channel.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ChannelEngine.Channel.ApiClient.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ChannelEngine.Channel.ApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get Cancellations Gets all cancellations created since the supplied date.
        /// </summary>
        /// <exception cref="ChannelEngine.Channel.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createdSince"></param>
        /// <returns>CollectionOfChannelCancellationResponse</returns>
        public CollectionOfChannelCancellationResponse CancellationIndex (DateTime? createdSince)
        {
             ApiResponse<CollectionOfChannelCancellationResponse> localVarResponse = CancellationIndexWithHttpInfo(createdSince);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Cancellations Gets all cancellations created since the supplied date.
        /// </summary>
        /// <exception cref="ChannelEngine.Channel.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createdSince"></param>
        /// <returns>ApiResponse of CollectionOfChannelCancellationResponse</returns>
        public ApiResponse< CollectionOfChannelCancellationResponse > CancellationIndexWithHttpInfo (DateTime? createdSince)
        {
            // verify the required parameter 'createdSince' is set
            if (createdSince == null)
                throw new ApiException(400, "Missing required parameter 'createdSince' when calling CancellationApi->CancellationIndex");

            var localVarPath = "/v2/cancellations";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (createdSince != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "createdSince", createdSince)); // query parameter

            // authentication (apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apikey")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apikey", this.Configuration.GetApiKeyWithPrefix("apikey")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CancellationIndex", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CollectionOfChannelCancellationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CollectionOfChannelCancellationResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CollectionOfChannelCancellationResponse)));
        }

        /// <summary>
        /// Get Cancellations Gets all cancellations created since the supplied date.
        /// </summary>
        /// <exception cref="ChannelEngine.Channel.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createdSince"></param>
        /// <returns>Task of CollectionOfChannelCancellationResponse</returns>
        public async System.Threading.Tasks.Task<CollectionOfChannelCancellationResponse> CancellationIndexAsync (DateTime? createdSince)
        {
             ApiResponse<CollectionOfChannelCancellationResponse> localVarResponse = await CancellationIndexAsyncWithHttpInfo(createdSince);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Cancellations Gets all cancellations created since the supplied date.
        /// </summary>
        /// <exception cref="ChannelEngine.Channel.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createdSince"></param>
        /// <returns>Task of ApiResponse (CollectionOfChannelCancellationResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CollectionOfChannelCancellationResponse>> CancellationIndexAsyncWithHttpInfo (DateTime? createdSince)
        {
            // verify the required parameter 'createdSince' is set
            if (createdSince == null)
                throw new ApiException(400, "Missing required parameter 'createdSince' when calling CancellationApi->CancellationIndex");

            var localVarPath = "/v2/cancellations";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (createdSince != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "createdSince", createdSince)); // query parameter

            // authentication (apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apikey")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apikey", this.Configuration.GetApiKeyWithPrefix("apikey")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CancellationIndex", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CollectionOfChannelCancellationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CollectionOfChannelCancellationResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CollectionOfChannelCancellationResponse)));
        }

    }
}
