/* 
 * ChannelEngine Channel API
 *
 * ChannelEngine API for channels
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = ChannelEngine.Channel.ApiClient.Client.SwaggerDateConverter;

namespace ChannelEngine.Channel.ApiClient.Model
{
    /// <summary>
    /// ChannelOrderRequest
    /// </summary>
    [DataContract]
    public partial class ChannelOrderRequest :  IEquatable<ChannelOrderRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChannelOrderRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ChannelOrderRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ChannelOrderRequest" /> class.
        /// </summary>
        /// <param name="channelOrderNo">The unique order reference used by the Channel (required).</param>
        /// <param name="lines">The order lines (required).</param>
        /// <param name="phone">The customer&#39;s telephone number.</param>
        /// <param name="email">The customer&#39;s email (required).</param>
        /// <param name="companyRegistrationNo">Optional. A company&#39;s chamber of commerce number.</param>
        /// <param name="vatNo">Optional. A company&#39;s VAT number.</param>
        /// <param name="paymentMethod">The payment method used on the order (required).</param>
        /// <param name="shippingCostsInclVat">The shipping fee including VAT  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering). (required).</param>
        /// <param name="currencyCode">The currency code for the amounts of the order (required).</param>
        /// <param name="orderDate">The date the order was done (required).</param>
        /// <param name="channelCustomerNo">The unique customer reference used by the channel.</param>
        /// <param name="billingAddress">The billing or invoice address (required).</param>
        /// <param name="shippingAddress">The shipping address (required).</param>
        /// <param name="extraData">Extra data on the order.</param>
        public ChannelOrderRequest(string channelOrderNo = default(string), List<ChannelOrderLineRequest> lines = default(List<ChannelOrderLineRequest>), string phone = default(string), string email = default(string), string companyRegistrationNo = default(string), string vatNo = default(string), string paymentMethod = default(string), decimal? shippingCostsInclVat = default(decimal?), string currencyCode = default(string), DateTime? orderDate = default(DateTime?), string channelCustomerNo = default(string), Address billingAddress = default(Address), Address shippingAddress = default(Address), Dictionary<string, string> extraData = default(Dictionary<string, string>))
        {
            // to ensure "channelOrderNo" is required (not null)
            if (channelOrderNo == null)
            {
                throw new InvalidDataException("channelOrderNo is a required property for ChannelOrderRequest and cannot be null");
            }
            else
            {
                this.ChannelOrderNo = channelOrderNo;
            }
            // to ensure "lines" is required (not null)
            if (lines == null)
            {
                throw new InvalidDataException("lines is a required property for ChannelOrderRequest and cannot be null");
            }
            else
            {
                this.Lines = lines;
            }
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new InvalidDataException("email is a required property for ChannelOrderRequest and cannot be null");
            }
            else
            {
                this.Email = email;
            }
            // to ensure "paymentMethod" is required (not null)
            if (paymentMethod == null)
            {
                throw new InvalidDataException("paymentMethod is a required property for ChannelOrderRequest and cannot be null");
            }
            else
            {
                this.PaymentMethod = paymentMethod;
            }
            // to ensure "shippingCostsInclVat" is required (not null)
            if (shippingCostsInclVat == null)
            {
                throw new InvalidDataException("shippingCostsInclVat is a required property for ChannelOrderRequest and cannot be null");
            }
            else
            {
                this.ShippingCostsInclVat = shippingCostsInclVat;
            }
            // to ensure "currencyCode" is required (not null)
            if (currencyCode == null)
            {
                throw new InvalidDataException("currencyCode is a required property for ChannelOrderRequest and cannot be null");
            }
            else
            {
                this.CurrencyCode = currencyCode;
            }
            // to ensure "orderDate" is required (not null)
            if (orderDate == null)
            {
                throw new InvalidDataException("orderDate is a required property for ChannelOrderRequest and cannot be null");
            }
            else
            {
                this.OrderDate = orderDate;
            }
            // to ensure "billingAddress" is required (not null)
            if (billingAddress == null)
            {
                throw new InvalidDataException("billingAddress is a required property for ChannelOrderRequest and cannot be null");
            }
            else
            {
                this.BillingAddress = billingAddress;
            }
            // to ensure "shippingAddress" is required (not null)
            if (shippingAddress == null)
            {
                throw new InvalidDataException("shippingAddress is a required property for ChannelOrderRequest and cannot be null");
            }
            else
            {
                this.ShippingAddress = shippingAddress;
            }
            this.Phone = phone;
            this.CompanyRegistrationNo = companyRegistrationNo;
            this.VatNo = vatNo;
            this.ChannelCustomerNo = channelCustomerNo;
            this.ExtraData = extraData;
        }
        
        /// <summary>
        /// The unique order reference used by the Channel
        /// </summary>
        /// <value>The unique order reference used by the Channel</value>
        [DataMember(Name="ChannelOrderNo", EmitDefaultValue=false)]
        public string ChannelOrderNo { get; set; }

        /// <summary>
        /// The order lines
        /// </summary>
        /// <value>The order lines</value>
        [DataMember(Name="Lines", EmitDefaultValue=false)]
        public List<ChannelOrderLineRequest> Lines { get; set; }

        /// <summary>
        /// The customer&#39;s telephone number
        /// </summary>
        /// <value>The customer&#39;s telephone number</value>
        [DataMember(Name="Phone", EmitDefaultValue=false)]
        public string Phone { get; set; }

        /// <summary>
        /// The customer&#39;s email
        /// </summary>
        /// <value>The customer&#39;s email</value>
        [DataMember(Name="Email", EmitDefaultValue=false)]
        public string Email { get; set; }

        /// <summary>
        /// Optional. A company&#39;s chamber of commerce number
        /// </summary>
        /// <value>Optional. A company&#39;s chamber of commerce number</value>
        [DataMember(Name="CompanyRegistrationNo", EmitDefaultValue=false)]
        public string CompanyRegistrationNo { get; set; }

        /// <summary>
        /// Optional. A company&#39;s VAT number
        /// </summary>
        /// <value>Optional. A company&#39;s VAT number</value>
        [DataMember(Name="VatNo", EmitDefaultValue=false)]
        public string VatNo { get; set; }

        /// <summary>
        /// The payment method used on the order
        /// </summary>
        /// <value>The payment method used on the order</value>
        [DataMember(Name="PaymentMethod", EmitDefaultValue=false)]
        public string PaymentMethod { get; set; }

        /// <summary>
        /// The shipping fee including VAT  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering).
        /// </summary>
        /// <value>The shipping fee including VAT  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering).</value>
        [DataMember(Name="ShippingCostsInclVat", EmitDefaultValue=false)]
        public decimal? ShippingCostsInclVat { get; set; }

        /// <summary>
        /// The currency code for the amounts of the order
        /// </summary>
        /// <value>The currency code for the amounts of the order</value>
        [DataMember(Name="CurrencyCode", EmitDefaultValue=false)]
        public string CurrencyCode { get; set; }

        /// <summary>
        /// The date the order was done
        /// </summary>
        /// <value>The date the order was done</value>
        [DataMember(Name="OrderDate", EmitDefaultValue=false)]
        public DateTime? OrderDate { get; set; }

        /// <summary>
        /// The unique customer reference used by the channel
        /// </summary>
        /// <value>The unique customer reference used by the channel</value>
        [DataMember(Name="ChannelCustomerNo", EmitDefaultValue=false)]
        public string ChannelCustomerNo { get; set; }

        /// <summary>
        /// The billing or invoice address
        /// </summary>
        /// <value>The billing or invoice address</value>
        [DataMember(Name="BillingAddress", EmitDefaultValue=false)]
        public Address BillingAddress { get; set; }

        /// <summary>
        /// The shipping address
        /// </summary>
        /// <value>The shipping address</value>
        [DataMember(Name="ShippingAddress", EmitDefaultValue=false)]
        public Address ShippingAddress { get; set; }

        /// <summary>
        /// Extra data on the order
        /// </summary>
        /// <value>Extra data on the order</value>
        [DataMember(Name="ExtraData", EmitDefaultValue=false)]
        public Dictionary<string, string> ExtraData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ChannelOrderRequest {\n");
            sb.Append("  ChannelOrderNo: ").Append(ChannelOrderNo).Append("\n");
            sb.Append("  Lines: ").Append(Lines).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  CompanyRegistrationNo: ").Append(CompanyRegistrationNo).Append("\n");
            sb.Append("  VatNo: ").Append(VatNo).Append("\n");
            sb.Append("  PaymentMethod: ").Append(PaymentMethod).Append("\n");
            sb.Append("  ShippingCostsInclVat: ").Append(ShippingCostsInclVat).Append("\n");
            sb.Append("  CurrencyCode: ").Append(CurrencyCode).Append("\n");
            sb.Append("  OrderDate: ").Append(OrderDate).Append("\n");
            sb.Append("  ChannelCustomerNo: ").Append(ChannelCustomerNo).Append("\n");
            sb.Append("  BillingAddress: ").Append(BillingAddress).Append("\n");
            sb.Append("  ShippingAddress: ").Append(ShippingAddress).Append("\n");
            sb.Append("  ExtraData: ").Append(ExtraData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ChannelOrderRequest);
        }

        /// <summary>
        /// Returns true if ChannelOrderRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ChannelOrderRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ChannelOrderRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ChannelOrderNo == input.ChannelOrderNo ||
                    (this.ChannelOrderNo != null &&
                    this.ChannelOrderNo.Equals(input.ChannelOrderNo))
                ) && 
                (
                    this.Lines == input.Lines ||
                    this.Lines != null &&
                    this.Lines.SequenceEqual(input.Lines)
                ) && 
                (
                    this.Phone == input.Phone ||
                    (this.Phone != null &&
                    this.Phone.Equals(input.Phone))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.CompanyRegistrationNo == input.CompanyRegistrationNo ||
                    (this.CompanyRegistrationNo != null &&
                    this.CompanyRegistrationNo.Equals(input.CompanyRegistrationNo))
                ) && 
                (
                    this.VatNo == input.VatNo ||
                    (this.VatNo != null &&
                    this.VatNo.Equals(input.VatNo))
                ) && 
                (
                    this.PaymentMethod == input.PaymentMethod ||
                    (this.PaymentMethod != null &&
                    this.PaymentMethod.Equals(input.PaymentMethod))
                ) && 
                (
                    this.ShippingCostsInclVat == input.ShippingCostsInclVat ||
                    (this.ShippingCostsInclVat != null &&
                    this.ShippingCostsInclVat.Equals(input.ShippingCostsInclVat))
                ) && 
                (
                    this.CurrencyCode == input.CurrencyCode ||
                    (this.CurrencyCode != null &&
                    this.CurrencyCode.Equals(input.CurrencyCode))
                ) && 
                (
                    this.OrderDate == input.OrderDate ||
                    (this.OrderDate != null &&
                    this.OrderDate.Equals(input.OrderDate))
                ) && 
                (
                    this.ChannelCustomerNo == input.ChannelCustomerNo ||
                    (this.ChannelCustomerNo != null &&
                    this.ChannelCustomerNo.Equals(input.ChannelCustomerNo))
                ) && 
                (
                    this.BillingAddress == input.BillingAddress ||
                    (this.BillingAddress != null &&
                    this.BillingAddress.Equals(input.BillingAddress))
                ) && 
                (
                    this.ShippingAddress == input.ShippingAddress ||
                    (this.ShippingAddress != null &&
                    this.ShippingAddress.Equals(input.ShippingAddress))
                ) && 
                (
                    this.ExtraData == input.ExtraData ||
                    this.ExtraData != null &&
                    this.ExtraData.SequenceEqual(input.ExtraData)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ChannelOrderNo != null)
                    hashCode = hashCode * 59 + this.ChannelOrderNo.GetHashCode();
                if (this.Lines != null)
                    hashCode = hashCode * 59 + this.Lines.GetHashCode();
                if (this.Phone != null)
                    hashCode = hashCode * 59 + this.Phone.GetHashCode();
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                if (this.CompanyRegistrationNo != null)
                    hashCode = hashCode * 59 + this.CompanyRegistrationNo.GetHashCode();
                if (this.VatNo != null)
                    hashCode = hashCode * 59 + this.VatNo.GetHashCode();
                if (this.PaymentMethod != null)
                    hashCode = hashCode * 59 + this.PaymentMethod.GetHashCode();
                if (this.ShippingCostsInclVat != null)
                    hashCode = hashCode * 59 + this.ShippingCostsInclVat.GetHashCode();
                if (this.CurrencyCode != null)
                    hashCode = hashCode * 59 + this.CurrencyCode.GetHashCode();
                if (this.OrderDate != null)
                    hashCode = hashCode * 59 + this.OrderDate.GetHashCode();
                if (this.ChannelCustomerNo != null)
                    hashCode = hashCode * 59 + this.ChannelCustomerNo.GetHashCode();
                if (this.BillingAddress != null)
                    hashCode = hashCode * 59 + this.BillingAddress.GetHashCode();
                if (this.ShippingAddress != null)
                    hashCode = hashCode * 59 + this.ShippingAddress.GetHashCode();
                if (this.ExtraData != null)
                    hashCode = hashCode * 59 + this.ExtraData.GetHashCode();
                return hashCode;
            }
        }
    }

}
